# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@master
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    # Runs a single command using the runners shell
    - name: Run the script
      run: python mappying_terraform.py | tee example/policy.tf
      env:
        SYSDIG_API_KEY: ${{ secrets.SYSDIG_API_KEY }}

    # Runs a set of commands using the runners shell
    - name: 'Install terraform-provider-sysdig'
      run: |
        wget https://github.com/draios/terraform-provider-sysdig/releases/download/v0.3.0/terraform-provider-sysdig-linux-amd64.tar.gz
        tar -xvf terraform-provider-sysdig-linux-amd64.tar.gz
        mv terraform-provider-sysdig_v0.3.0 ${TERRAFORM_CLI_PATH}
    - name: Run terraform validate and plan to check the format
      run: |
        terraform providers
        terraform init -plugin-dir=${TERRAFORM_CLI_PATH}
        terraform validate
      working-directory: example
